# Generated by Django 4.1.3 on 2022-11-24 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pi3', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='data_devolucao',
        ),
    ]
