# Generated by Django 4.1.3 on 2022-11-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi3', '0002_remove_emprestimos_data_devolucao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='data_previ_dev',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
