# Generated by Django 4.1.3 on 2022-11-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi3', '0003_alter_emprestimos_data_devolucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(auto_now_add=True),
        ),
    ]
