# Generated by Django 4.1.3 on 2022-11-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi3', '0004_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hist_Empr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('titulo', models.CharField(max_length=200)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='emprestimos',
            name='data_devolucao',
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_aquisicao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
